# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT

FROM python:3.14.3-slim
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV POETRY_VIRTUALENVS_IN_PROJECT=true
# https://stackoverflow.com/questions/61863806/stuck-in-watching-for-file-changes-with-statreloader
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN pip install poetry==1.8.5
RUN apt-get update && apt-get install -y \
  gcc \
  curl \
  git \
  libxml2-dev \
  libpq-dev \
  libxslt-dev
RUN sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /bin
COPY poetry.lock pyproject.toml /app
RUN poetry lock --no-update
RUN poetry install
COPY . /app
