# SPDX-FileCopyrightText: Copyright (c) 2023-2026 Almaz Ilaletdinov <a.ilaletdinov@yandex.ru>
# SPDX-License-Identifier: MIT
---
version: 3

tasks:

  compose-setup:
    cmds:
      - docker compose build app
      - docker compose pull postgres redis

  compose-run:
    cmds:
      - docker compose up -d

  compose-stop:
    cmds:
      - docker compose down

  compose-bash:
    cmds:
      - docker compose run app bash

  compose-tests:
    cmds:
      - docker compose run app task tests

  compose-lint:
    cmds:
      - docker compose run app task lint

  tests:
    deps: [syntax-check,type-check]
    cmds:
      - poetry run pytest src -m 'not integration' -vv

  test:
    deps: 
      - syntax-check
      - type-check
    cmds:
      - cd src
      - poetry run pytest {{.CLI_ARGS}}

  shell:
    cmds:
      - poetry run python src/manage.py shell_plus

  migrate:
    cmds:
      - poetry run python src/manage.py makemigrations
      - poetry run python src/manage.py migrate

  fmt:
    cmds:
      - poetry run ruff check src --fix --fix-only

  lint:
    cmds:
      - poetry run ruff check src --output-format=concise
      - poetry run flake8 src
      - poetry run mypy src

  syntax-check:
    cmds:
      - poetry run ruff check src --select=F --ignore=F401,F841

  type-check:
    cmds:
      - poetry run mypy src

  clean:
    cmds:
      - git clean -f -d -x -e .env -e src/revive-code-bot.private-key.pem
      - docker rmi revive-code-bot-app -f
