# Generated by Django 5.0.6 on 2024-07-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghrepo',
            name='scheduling',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to='django_celery_beat.crontabschedule',
            ),
            preserve_default=False,
        ),
    ]
