# Generated by Django 5.0.6 on 2024-06-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ghrepo_installation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ghinstallation',
            table='gh_installations',
        ),
        migrations.AlterModelTable(
            name='ghrepo',
            table='gh_repos',
        ),
    ]
