# Generated by Django 5.0.6 on 2024-06-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_installation_ghrepo_gh_installation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghrepo',
            name='has_webhook',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
