# Generated by Django 5.0.6 on 2024-07-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_ghrepo_has_webhook'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('date', models.DateField()),
                ('gh_repo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ghrepo')),
            ],
            options={
                'db_table': 'touch_records',
            },
        ),
    ]
