# Generated by Django 5.1.8 on 2025-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0006_processtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('in_process', 'In Process'),
                    ('success', 'Success'),
                    ('failed', 'Failed'),
                ],
                max_length=16,
            ),
        ),
    ]
