# Generated by Django 5.0.6 on 2024-07-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_touchrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghrepo',
            name='gh_installation',
        ),
        migrations.AddField(
            model_name='ghrepo',
            name='installation_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GhInstallation',
        ),
    ]
