# Generated by Django 5.2 on 2025-04-07 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_processtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='repo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.ghrepo'),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=8),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='traceback',
            field=models.TextField(default=str),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
