# Generated by Django 5.2.7 on 2025-11-24 18:34

import random

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from main.services.croniq_task import CroniqTask
from main.services.github_objs.github_client import github_repo
from main.services.revive_config.default_revive_config import DefaultReviveConfig
from main.services.revive_config.gh_revive_config import GhReviveConfig
from main.services.revive_config.merged_config import MergedConfig


def _repo_configs(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    GhRepo = apps.get_model('main', 'GhRepo')
    RepoConfig = apps.get_model('main', 'RepoConfig')
    for repo_db_record in GhRepo.objects.filter(repoconfig__isnull=True):
        gh_repo = github_repo(repo_db_record.installation_id, repo_db_record.full_name)
        parsed_config = config.parse()
        config = MergedConfig.ctor(
            GhReviveConfig(
                gh_repo,
                DefaultReviveConfig(random.Random()),
            ),
        )
        RepoConfig.objects.create(
            repo=repo_db_record,
            cron_expression=parsed_config['cron'],
        )
        CroniqTask(repo_db_record.id).apply(
            parsed_config['cron'],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_processtask_status'),
    ]

    operations = [
        migrations.RunPython(_repo_configs),
    ]
